name: CI

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  this-one-fails:
    name: This one fails
    runs-on: ubuntu-20.04
    steps:
      - name: Fail
        run: |
          ls -al /whatever
      - name: Succeed
        id: publish
        run: |
          ls -al
      - name: This one is conditional
        if: ${{ failure() && steps.publish.conclusion == 'failure' }}
        run: |
          echo "This is just a test"
