name: Push

on:
  push:

jobs:
  failing-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Failing job
        run: exit 1

  create-issue:
    runs-on: ubuntu-latest
    if: ${{ always() && contains(join(needs.*.result, ','), 'failure') }}
    needs: [ failing-job ]
    steps:
      - name: Check whether the issue already exists
        id: check-issue
        run: |
          curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ github.token }}" \
            https://api.github.com/repos/$GITHUB_REPOSITORY/issues | grep "CI run failed"
      - name: Test
        run: echo ${{ steps.check-issue.outputs }}
      - name: Create issue
        uses: dacbd/create-issue-action@main
        with:
          token: ${{ github.token }}
          title: CI run failed
          body: my new issue
