name: Push

on:
  push:
    branches:
      - main

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.AUTH_TOKEN }}
          repository: Gmerold/test-repo-2
          event-type: operator-changed
          client-payload: '{"github_ref": "${{ github.ref_name }}", "github_repo": "${{ github.repository }}"}'
