name: Push

on:
  push:

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Dispatch
        run: |
          curl -X POST --verbose
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          --data '{"event_type": "operator_change", "client_payload": { "github_ref": "${{ github.ref }}", "github_repo": "${{ github.repository }}" }}' https://api.github.com/repos/Gmerold/test-repo-2/dispatches
